{{- $top := . -}}
{{- range $volume := .Values.localVolumes -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-provisioner-{{ $volume.name }}
provisioner: rancher.io/local-path
volumeBindingMode: {{ $volume.bindingMode | default "WaitForFirstConsumer" }}
reclaimPolicy: {{ $volume.reclaimPolicy | default "Retain" }}
{{ end }}