defaultNamespace: kube-system

dependsOn:
  - name: homecentr-infra-metallb
  - name: homecentr-infra-metallb-configuration

helm:
  chart: traefik
  version: v20.5.1
  repo: https://traefik.github.io/charts
  releaseName: ingress
  values:
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: "ingress"

targetCustomizations:
  - name: lab
    clusterSelector:
      matchLabels:
        env: lab
    helm:
      values:
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: 10.1.8.130
  
  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
    helm:
      values:
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: 10.1.2.130