defaultNamespace: kube-system

dependsOn:
  - name: homecentr-infra-metallb
  - name: homecentr-infra-priority-classes

helm:
  chart: "./chart" # local chart
  repo: ""
  version: ""
  releaseName: metallb
  
targetCustomizations:
  - name: lab
    clusterSelector:
      matchLabels:
        env: lab
    helm:
      valuesFiles:
      - values-lab.yml

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
    helm:
      valuesFiles:
      - values-prod.yml
