defaultNamespace: metallb-system

dependsOn:
  - name: homecentr-infra-metallb

# The custom resources must be in a separate bundle because using helm dependency 
# creates a race condition when the resources are created before kubernetes api accepts them

helm:
  chart: "./chart" # local chart
  repo: ""
  version: ""
  releaseName: metallb-configuration

targetCustomizations:
  - name: lab
    clusterSelector:
      matchLabels:
        env: lab
    helm:
      valuesFiles:
      - values-lab.yml

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
    helm:
      valuesFiles:
      - values-prod.yml