apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-hook"
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "1"
