apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name | quote }}
  namespace: kube-system
  labels:
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    dummy: "AAAA"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: labeler
        image: gcr.io/google_containers/hyperkube:v1.9.7
        command:
        - kubectl
        - label
        - ns
        - {{ .Release.Namespace }}
        - dummy=true
      restartPolicy: Never
      serviceAccountName: fleet-local