defaultNamespace: cert-manager

paused: true

helm:
  chart: cert-manager
  version: v1.10.1
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  values:
      installCRDs: true
      webhook:
        securePort: 10222
        podAnnotations:
          container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
          seccomp.security.alpha.kubernetes.io/pod: runtime/default
        containerSecurityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 2000
          readOnlyRootFilesystem: true
          capabilities:
              drop:
              - all
      cainjector:
        podAnnotations:
          container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
          seccomp.security.alpha.kubernetes.io/pod: runtime/default
        containerSecurityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 2000
          readOnlyRootFilesystem: true
          capabilities:
              drop:
              - all
      podAnnotations:
        container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          memory: 128Mi
      containerSecurityContext:
        allowPrivilegeEscalation: false
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
        readOnlyRootFilesystem: true
        capabilities:
            drop:
            - all

targetCustomizations:
  - name: lab
    clusterSelector:
      matchLabels:
        env: lab
    helm:
      values:
        webhook:
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              memory: 10Mi
        caInjector:
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              memory: 10Mi

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
    helm:
      values:
        webhook:
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              memory: 128Mi
        caInjector:
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              memory: 128Mi