cert-manager:
  installCRDs: true
  webhook:
    securePort: "{{ certmanager_webhook_secure_port }}"
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      readOnlyRootFilesystem: true
      capabilities:
          drop:
          - all
  cainjector:
    podAnnotations:
      container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
      seccomp.security.alpha.kubernetes.io/pod: runtime/default
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        memory: 128Mi
    containerSecurityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 2000
      readOnlyRootFilesystem: true
      capabilities:
          drop:
          - all
  podAnnotations:
    container.apparmor.security.beta.kubernetes.io/cert-manager: runtime/default
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      memory: 128Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    privileged: false
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 2000
    readOnlyRootFilesystem: true
    capabilities:
        drop:
        - all