prometheus:
  scrapeAnnotations: true
controller:
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 512Mi
speaker:
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 512Mi